### ISSUE TITLE
Mishandling of socket errors

### ISSUE THREAD

**Issue by ecto** [ecto/bolt#5]
Looks like the err event is throwing, should just remove socket from pool

```
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: ECONNRESET, Connection reset by peer
    at Socket._writeImpl (net.js:159:14)
    at Socket._writeOut (net.js:444:25)
    at Socket.write (net.js:377:17)
```

**Comment by ecto** [comment]
fixed with red is pub sub

**Comment by ecto** [comment]
damn you autocorrect
